"""Contracts for the pure artifact consumer, never runtime or GPU measurements.

Every fixture here is synthetic and says so. A positive fixture proves the
parser and the recomputation contract only; it establishes no measurement and
admits nothing. Each tampering test restates the outer artifact hash, so what
catches the defect is the semantic consumer rather than the checksum reader.
"""
import copy
import hashlib
import json
from pathlib import Path
import re

import pytest

from prismaquant.measured_runtime_prices import RuntimePriceError
from prismaquant import full_engine_resource_report as consumer
from prismaquant.full_engine_resource_report import (
    DOMAINS, ENVELOPE_MEMBERS, PLACEMENT_OBLIGATION, REPORT_SCHEMA, TERMS,
    _placement_obligation, consume_full_engine_resource_report,
    read_full_engine_resource_report,
)

MODULE = Path(consumer.__file__)
#: Emitted by the Tessera producer rather than hand-written, apart from the
#: three members the raw ledger cannot supply and the producer refuses to
#: default (`reference`, `workload`, `execution`). Regenerated by running
#: `experiments.full_engine_resource_partition.assemble_full_engine_resource_report`
#: over `tests/fixtures/full_engine_resource_ledger.json` in the producer tree.
#:
#: **Synthetic, and a refusal path only.** The capture it derives from says on
#: its face that it is a CPU parser fixture, and that marker travels into
#: `identity.fixture_provenance`, so this artifact can never read as a
#: measurement. No live capture of this report exists; nothing emits it in
#: production today.
SUPPLIED = Path(__file__).resolve().parent / "fixtures" / "full_engine_resource_report.synthetic.json"
#: The same synthetic capture with the one engine step it ran declared over it,
#: assembled by the same producer entry point. It is a refusal fixture too: it
#: proves the complete-coverage shapes read and recompute, and it establishes no
#: measurement. No live capture of this report exists.
STEPPED = (Path(__file__).resolve().parent / "fixtures"
           / "full_engine_resource_report.synthetic_steps.json")

#: The off-step peak scope sentence the producer emits while `worker_startup`
#: is open. No check reads it; it is restated here so the fixtures carry the
#: producer's own wording rather than a paraphrase.
OPEN_STARTUP_PEAK_SCOPE = (
    "off-step transient bytes observed in this capture; a floor rather than the "
    "startup peak, because worker_startup is open and the prefix before the "
    "recorder attached is unobserved")


def written(tmp_path, report, name="report.json"):
    """Write a report and restate its hash, so tampering reaches the consumer."""
    raw = (report if isinstance(report, bytes)
           else json.dumps(report, sort_keys=True, allow_nan=False).encode())
    path = tmp_path / name
    path.write_bytes(raw)
    return {"path": str(path), "sha256": hashlib.sha256(raw).hexdigest()}


def supplied():
    return json.loads(SUPPLIED.read_bytes())


def stepped():
    return json.loads(STEPPED.read_bytes())


def consume(tmp_path, report, **kwargs):
    return consume_full_engine_resource_report(written(tmp_path, report), root=tmp_path, **kwargs)


def mutated(mutate):
    report = supplied()
    mutate(report)
    return report


# --------------------------------------------------------------------------
# The supplied artifact. Its correct verdict is a refusal that names why.
# --------------------------------------------------------------------------

def test_the_supplied_synthetic_report_refuses_and_names_its_open_domains_and_unclassified_allocation(tmp_path):
    verdict = consume(tmp_path, supplied())
    assert verdict.open_domains == ("worker_startup", "external_closure",
                                    "provenance_admission", "cache_capacity", "timing_partition")
    assert verdict.unclassified_allocations == ("0:4608:1",)
    assert verdict.expressible_terms == ()
    assert verdict.recomputed_scalar_budget_bytes is None
    for name in verdict.open_domains:
        assert any(name in reason for reason in verdict.blocking)
    assert any("0:4608:1" in reason and "unclassified" in reason for reason in verdict.blocking)
    assert "synthetic" in verdict.fixture_provenance


def test_the_consumer_recomputes_the_supplied_report_without_disagreeing_with_it(tmp_path):
    """Every number the producer declares reproduces from the raw observations."""
    assert consume(tmp_path, supplied()).disagreements == ()


def test_the_consumer_reads_the_artifact_and_never_the_serving_runtime():
    """The artifact travels; the code does not (AGENTS.md principle 5)."""
    source = MODULE.read_text(encoding="utf-8")
    assert re.search(r"^\s*(import|from)\s+\S*tessera", source, flags=re.MULTILINE) is None
    assert "subprocess" not in source and "importlib" not in source
    mentions = re.findall(r"tessera\S*", source)
    assert mentions, "the schema the artifact declares about itself should be named"
    for mention in mentions:
        # Every mention is part of a schema identifier, never a module path.
        assert re.match(r"tessera\.full_engine_resource_(report|identity|partition)\.v1",
                        mention), mention


def test_the_admission_gate_is_the_only_reader_of_this_recomputed_partition(tmp_path):
    """`admit_fixed_resources` reads it, and nothing else in the package may.

    The gate is the design's last prerequisite row ("integrate allocator
    admission"); its own contracts live in
    `tests/test_runtime_fixed_resource_admission.py`. An inline resource claim
    still refuses before any recomputation runs, because a claim is not
    evidence whatever it says.
    """
    from types import SimpleNamespace
    from prismaquant.runtime_provenance import admit_fixed_resources
    reference = written(tmp_path, {"full_model_resources": {"resident_bytes": 0}}, "fixed.json")
    table = SimpleNamespace(source_path=str(tmp_path / "table.json"),
                            fixed_resources_receipt_path=reference["path"],
                            fixed_resources_receipt_sha256=reference["sha256"])
    with pytest.raises(RuntimePriceError, match="must reference one recomputable"):
        admit_fixed_resources(table, {})
    root = MODULE.parent
    importers = [path.name for path in sorted(root.glob("*.py"))
                 if "full_engine_resource_report" in path.read_text(encoding="utf-8")
                 and path != MODULE]
    assert importers == ["runtime_provenance.py"]


# --------------------------------------------------------------------------
# The keystone: `derived` is a claim, never an input.
# --------------------------------------------------------------------------

@pytest.mark.parametrize("term", TERMS)
def test_a_changed_derived_term_refuses_because_the_recomputation_disagrees(tmp_path, term):
    """The keystone, over every term. A candidate term is a per-unit table, so
    the claim is written in that shape and reaches the recomputation rather
    than stopping at the reader; a scalar in its place refuses too, which
    `test_a_per_unit_term_that_arrives_as_a_scalar_refuses` pins separately."""
    charged = ({"unit": 4096} if term in consumer.PER_UNIT_TERMS else 4096)

    def mutate(report):
        report["derived"]["terms"][term] = charged
        report["derived"]["scope"]["unavailable_terms"].remove(term)
    verdict = consume(tmp_path, mutated(mutate))
    # Every term of this report recomputes to null, so the claim disagrees on
    # its whole value; the per-unit form of the message is exercised where the
    # terms are genuinely expressible, in the closed fixture below.
    assert any(f"derived term {term} " in reason and "4096" in reason
               for reason in verdict.disagreements)
    assert any("unavailable terms" in reason for reason in verdict.disagreements)


def test_a_changed_derived_scalar_budget_refuses_because_the_recomputation_disagrees(tmp_path):
    verdict = consume(tmp_path, mutated(lambda r: r["derived"].update(scalar_budget_bytes=20 * 1024**3)))
    assert any("scalar budget is 21474836480" in reason and "recomputes None" in reason
               for reason in verdict.disagreements)


def test_a_zero_derived_total_is_not_an_unknown_one(tmp_path):
    """`None` and `0` are different claims and the comparison is type-strict."""
    verdict = consume(tmp_path, mutated(lambda r: r["derived"]["terms"].update(fixed_scratch=0)))
    assert any("derived term fixed_scratch is 0" in reason for reason in verdict.disagreements)


def test_a_changed_observed_live_peak_refuses_as_not_the_simultaneous_maximum(tmp_path):
    """512 + 512 + 1024 is a sum of per-allocation maxima, not a peak."""
    verdict = consume(tmp_path, mutated(
        lambda r: r["observations"].update(torch_observed_live_peak_bytes=2048)))
    assert any("maximum simultaneous sum" in reason for reason in verdict.disagreements)


# --------------------------------------------------------------------------
# Envelope and reader refusals, before any arithmetic.
# --------------------------------------------------------------------------

@pytest.mark.parametrize("schema", [None, "", "tessera.full_engine_resource_capture.v1",
                                    "tessera.full_engine_raw_resource_ledger.v1",
                                    "tessera.full_engine_resource_report.v2"])
def test_a_foreign_schema_refuses(tmp_path, schema):
    report = supplied()
    if schema is None:
        del report["schema"]
    else:
        report["schema"] = schema
    with pytest.raises(RuntimePriceError, match="unsupported schema"):
        consume(tmp_path, report)


@pytest.mark.parametrize("member", ENVELOPE_MEMBERS)
def test_a_missing_envelope_member_refuses(tmp_path, member):
    with pytest.raises(RuntimePriceError, match="missing envelope member " + member):
        consume(tmp_path, mutated(lambda r: r.pop(member)))


def test_an_unnamed_envelope_field_refuses(tmp_path):
    with pytest.raises(RuntimePriceError, match="expected exactly fields"):
        consume(tmp_path, mutated(lambda r: r.update(admission="qualified")))


def test_a_boolean_where_an_integer_is_declared_refuses(tmp_path):
    """`True` is an instance of `int` in Python. It is not one here."""
    with pytest.raises(RuntimePriceError, match="expected integer"):
        consume(tmp_path, mutated(
            lambda r: r["observations"]["torch_allocations"][0].update(bytes=True)))


@pytest.mark.parametrize("literal", [b"NaN", b"Infinity", b"-Infinity"])
def test_a_nonfinite_numeric_field_refuses(tmp_path, literal):
    """`json.loads` accepts these by default; the artifact reader does not."""
    raw = SUPPLIED.read_bytes().replace(b'"torch_observed_live_peak_bytes": 1536',
                                        b'"torch_observed_live_peak_bytes": ' + literal)
    assert literal in raw
    with pytest.raises(RuntimePriceError, match="invalid JSON artifact"):
        consume_full_engine_resource_report(written(tmp_path, raw), root=tmp_path)


def test_a_duplicate_json_key_refuses(tmp_path):
    raw = SUPPLIED.read_bytes().replace(b'"schema": "tessera.full_engine_resource_report.v1"',
                                        b'"schema": "tessera.full_engine_resource_report.v1",'
                                        b' "schema": "tessera.full_engine_resource_report.v1"', 1)
    with pytest.raises(RuntimePriceError, match="duplicate JSON key"):
        consume_full_engine_resource_report(written(tmp_path, raw), root=tmp_path)


def test_a_negative_size_refuses(tmp_path):
    with pytest.raises(RuntimePriceError, match="expected integer >= 0"):
        consume(tmp_path, mutated(
            lambda r: r["observations"]["torch_allocations"][0].update(bytes=-512)))


def test_an_unknown_enum_value_refuses(tmp_path):
    with pytest.raises(RuntimePriceError, match="unknown value"):
        consume(tmp_path, mutated(
            lambda r: r["observations"]["torch_allocations"][0].update(lifetime_scope="maybe")))


def test_a_tampered_report_that_keeps_its_old_hash_refuses_at_the_digest(tmp_path):
    report = mutated(lambda r: r["derived"].update(scalar_budget_bytes=1))
    reference = written(tmp_path, report)
    reference["sha256"] = hashlib.sha256(SUPPLIED.read_bytes()).hexdigest()
    with pytest.raises(RuntimePriceError, match="artifact SHA-256"):
        consume_full_engine_resource_report(reference, root=tmp_path)


# --------------------------------------------------------------------------
# The named refusals of the merged design.
# --------------------------------------------------------------------------

def test_a_reused_pointer_generation_refuses(tmp_path):
    def mutate(report):
        rows = report["observations"]["torch_allocations"]
        rows.append(copy.deepcopy(rows[0]))
    with pytest.raises(RuntimePriceError, match="pointer generation is reused"):
        consume(tmp_path, mutated(mutate))


def test_an_allocation_identity_that_hides_its_generation_refuses(tmp_path):
    with pytest.raises(RuntimePriceError, match="does not name its device, address and generation"):
        consume(tmp_path, mutated(
            lambda r: r["observations"]["torch_allocations"][2].update(allocation_id="0:4608")))


@pytest.mark.parametrize("mutation", ["completed_without_requested", "freed_before_allocated",
                                      "settled_out_of_order", "live_at_a_later_checkpoint"])
def test_a_live_free_mismatch_refuses(tmp_path, mutation):
    report = supplied()
    row = report["observations"]["torch_allocations"][2]
    if mutation == "completed_without_requested":
        row["free_requested_index"] = None
        with pytest.raises(RuntimePriceError, match="requested free"):
            consume(tmp_path, report)
    elif mutation == "freed_before_allocated":
        row.update(free_requested_index=2, free_completed_index=3)
        with pytest.raises(RuntimePriceError, match="must follow the allocation"):
            consume(tmp_path, report)
    elif mutation == "settled_out_of_order":
        row.update(free_requested_index=10, free_completed_index=9)
        with pytest.raises(RuntimePriceError, match="settle in order"):
            consume(tmp_path, report)
    else:
        # Freed at 7, yet the `unit_end` checkpoint at index 8 still owns it.
        row.update(free_requested_index=7, free_completed_index=7)
        verdict = consume(tmp_path, report)
        assert any("does not list the owned storages live at its index" in reason
                   for reason in verdict.disagreements)


@pytest.mark.parametrize("mutation", ["omitted_extent", "omitted_owner", "omitted_unit"])
def test_an_omitted_unit_owner_or_extent_refuses(tmp_path, mutation):
    report = supplied()
    if mutation == "omitted_extent":
        report["partition"]["membership"] = [report["partition"]["membership"][0]]
        expected = "not the ones this consumer classifies"
    elif mutation == "omitted_owner":
        report["observations"]["torch_allocations"][0]["observed_owners"] = ["embedding.weight"]
        expected = "another owner count"
    else:
        report["partition"]["units"] = []
        expected = "the partition's units are not the units this consumer recomputes"
    assert any(expected in reason for reason in consume(tmp_path, report).disagreements)


def test_a_duplicate_alias_refuses(tmp_path):
    def mutate(report):
        rows = report["observations"]["torch_allocations"]
        rows[2]["observed_owners"] = ["lm_head.weight"]
    assert any("duplicate alias claimed by two backings" in reason
               for reason in consume(tmp_path, mutated(mutate)).disagreements)


def test_a_repeated_alias_inside_one_storage_refuses(tmp_path):
    with pytest.raises(RuntimePriceError, match="duplicate entry"):
        consume(tmp_path, mutated(
            lambda r: r["observations"]["checkpoints"][0]["storages"][0].update(
                owners=["embedding.weight", "embedding.weight"])))


def test_a_candidate_and_fixed_overlap_refuses(tmp_path):
    def mutate(report):
        report["observations"]["torch_allocations"][0]["observed_categories"] = ["candidate", "fixed"]
    verdict = consume(tmp_path, mutated(mutate))
    assert any("claimed by two owner classes (candidate, fixed)" in reason
               for reason in verdict.disagreements)
    # It also stops being classified at all, which nulls every term.
    assert "0:4096:1" in verdict.unclassified_allocations


def test_a_missing_parent_segment_refuses(tmp_path):
    """A Torch suballocation and its CUDA segment are two views of one backing."""
    def mutate(report):
        report["observations"]["torch_allocations"][0]["allocator_block_bytes_observed"] = [256]
    assert any("no observed parent segment large enough" in reason
               for reason in consume(tmp_path, mutated(mutate)).disagreements)


@pytest.mark.parametrize("mutation", ["unknown_status", "handled_while_unavailable", "domain_issue"])
def test_an_unknown_allocation_api_refuses(tmp_path, mutation):
    report = supplied()
    domains = report["observations"]["cuda_argument_domains"]
    if mutation == "unknown_status":
        domains["status"] = "partially_observed"
        with pytest.raises(RuntimePriceError, match="unknown value"):
            consume(tmp_path, report)
        return
    if mutation == "handled_while_unavailable":
        domains["handled_api_keys"] = ["cudaMallocAsync"]
        expected = "declares itself unavailable"
    else:
        domains["issues"] = ["unhandled allocation API"]
        expected = "unresolved issues"
    assert any(expected in reason for reason in consume(tmp_path, report).disagreements)


@pytest.mark.parametrize("key", ["model_sha256", "runtime_manifest_sha256", "workload_sha256",
                                 "configuration_sha256", "assignment_sha256"])
def test_a_stale_source_workload_or_runtime_refuses(tmp_path, key):
    verdict = consume(tmp_path, supplied(), expected_run_identity={key: "b" * 64})
    assert any(f"stale {key}" in reason for reason in verdict.disagreements)


def test_a_calibration_identity_is_not_expressible_so_its_absence_blocks(tmp_path):
    """`identity.run` carries no `calibration_sha256`, so stale calibration can
    only be refused through the workload member, which carries none either."""
    assert "calibration_sha256" not in supplied()["identity"]["run"]
    verdict = consume(tmp_path, supplied(), expected_run_identity={"calibration_sha256": "b" * 64})
    assert any("declares no calibration_sha256" in reason for reason in verdict.disagreements)
    assert any("no calibration identity" in reason for reason in verdict.blocking)


def test_a_partition_of_another_run_refuses(tmp_path):
    def mutate(report):
        report["partition"]["identity"]["model_sha256"] = "b" * 64
    assert any("differs from the report identity" in reason
               for reason in consume(tmp_path, mutated(mutate)).disagreements)


def test_a_partition_of_another_capture_refuses(tmp_path):
    def mutate(report):
        report["partition"]["capture_sha256"] = "b" * 64
    assert any("names a different capture" in reason
               for reason in consume(tmp_path, mutated(mutate)).disagreements)


@pytest.mark.parametrize("domain", [name for name in DOMAINS if name != "history_join"])
def test_a_domain_that_closes_where_the_consumer_cannot_refuses(tmp_path, domain):
    """Altered cache capacity, a missing timing tail and overlapping streams
    all reach this consumer only as a domain state, because the report carries
    no KV, timing or stream observation to recompute."""
    def mutate(report):
        report["partition"]["domains"][domain] = {
            "state": "closed", "reason": None, "evidence": ["checkpoints"]}
    verdict = consume(tmp_path, mutated(mutate))
    assert any(f"calls domain {domain} closed where this consumer recomputes it as not closed"
               in reason for reason in verdict.disagreements)


def test_the_two_checkable_domains_close_only_on_their_own_observed_condition(tmp_path):
    """`history_join` reads the unattributed external records and
    `external_closure` reads the external native peak. The other four have no
    condition in this schema, which is why they stay open above."""
    assert consume(tmp_path, supplied()).disagreements == ()

    def unattributed(report):
        report["observations"]["unattributed_external_records"] = [{"record": 1}]
    assert any("calls domain history_join closed where this consumer recomputes it as not closed"
               in reason for reason in consume(tmp_path, mutated(unattributed)).disagreements)

    def external(report):
        report["observations"]["external_native_peak_bytes"] = 4096
    assert any("calls domain external_closure open where this consumer recomputes it as closed"
               in reason for reason in consume(tmp_path, mutated(external)).disagreements)


def test_the_owed_observations_are_named_and_null_rather_than_absent(tmp_path):
    """A capture that did not observe something says so by name.

    The four domains with no consumer-checkable closing condition would close
    on these; v1 carries each as an explicit null, so "not observed" is
    distinguishable from "the producer dropped it", and dropping one is a
    refusal rather than a silent gap.
    """
    report = supplied()
    assert set(consumer.OWED_OBSERVATIONS) <= set(report["observations"])
    assert all(report["observations"][name] is None for name in consumer.OWED_OBSERVATIONS)

    for name in consumer.OWED_OBSERVATIONS:
        def mutate(report, name=name):
            del report["observations"][name]
        with pytest.raises(RuntimePriceError, match="expected exactly fields"):
            consume(tmp_path, mutated(mutate))


@pytest.mark.parametrize("name", list(consumer.OWED_OBSERVATIONS))
def test_an_owed_observation_that_carries_a_value_refuses(tmp_path, name):
    """v1 defines no shape for these, so a value here is something no consumer
    can recompute a term or close a domain from. Reading one would be trusting
    the producer's own word, which is the failure this consumer exists to
    prevent."""
    def mutate(report):
        report["observations"][name] = [{"claimed": 4096}]
    with pytest.raises(RuntimePriceError, match="defines no shape for it"):
        consume(tmp_path, mutated(mutate))


def test_a_domain_that_closes_on_evidence_the_envelope_does_not_carry_refuses(tmp_path):
    """Evidence names an observation, and the consumer goes and looks."""
    def mutate(report):
        report["partition"]["domains"]["history_join"]["evidence"] = ["kv_measurements"]
    with pytest.raises(RuntimePriceError, match="names no observation this report carries"):
        consume(tmp_path, mutated(mutate))


def test_the_partition_owns_the_domains_and_derived_may_not_restate_them(tmp_path):
    """Two copies of one claim are two things that can drift apart. `derived`
    carries the numbers; `partition` carries the domain states the numbers
    depend on, and a `derived` that restates them is an unnamed field."""
    report = supplied()
    assert "domains" in report["partition"]
    assert "domains" not in report["derived"]

    def mutate(report):
        report["derived"]["domains"] = copy.deepcopy(report["partition"]["domains"])
    with pytest.raises(RuntimePriceError, match="expected exactly fields"):
        consume(tmp_path, mutated(mutate))


def test_a_domain_that_closes_without_evidence_refuses(tmp_path):
    def mutate(report):
        report["partition"]["domains"]["cache_capacity"] = {"state": "closed", "reason": None,
                                                            "evidence": []}
    with pytest.raises(RuntimePriceError, match="evidence must be present exactly when"):
        consume(tmp_path, mutated(mutate))


def test_a_foreign_rank_or_device_refuses(tmp_path):
    def mutate(report):
        rows = report["observations"]["torch_allocations"]
        rows[0]["allocation_id"] = "1:4096:1"
        for checkpoint in report["observations"]["checkpoints"]:
            for storage in checkpoint["storages"]:
                if storage["allocation_id"] == "0:4096:1":
                    storage["allocation_id"] = "1:4096:1"
        for row in report["partition"]["membership"]:
            if row["allocation_id"] == "0:4096:1":
                row["allocation_id"] = "1:4096:1"
    assert any("is on a foreign device" in reason
               for reason in consume(tmp_path, mutated(mutate)).disagreements)


@pytest.mark.parametrize("member,key,value", [
    ("execution", "topology", "tp2"),
    ("execution", "graph_mode", "graph"),
    ("execution", "residency", "streamed"),
])
def test_an_unsupported_boundary_refuses(tmp_path, member, key, value):
    with pytest.raises(RuntimePriceError, match="unsupported " + key):
        consume(tmp_path, mutated(lambda r: r[member].update({key: value})))


@pytest.mark.parametrize("key,value", [
    ("topology", "tp2_rank_sum"),
    ("allocation_scope", "host_and_device"),
    ("invariance", "every assignment the allocator may pick"),
])
def test_an_unsupported_derived_scope_refuses(tmp_path, key, value):
    with pytest.raises(RuntimePriceError, match="unsupported " + key):
        consume(tmp_path, mutated(lambda r: r["derived"]["scope"].update({key: value})))


@pytest.mark.parametrize("label", ["shared", "unknown"])
def test_assignment_dependent_shared_state_stays_unclassified_and_nulls_every_term(tmp_path, label):
    def mutate(report):
        report["observations"]["torch_allocations"][0]["observed_categories"] = [label]
    verdict = consume(tmp_path, mutated(mutate))
    assert "0:4096:1" in verdict.unclassified_allocations
    assert verdict.recomputed_terms == {name: None for name in TERMS}
    assert any("neither classification nor invariance" in reason for reason in verdict.blocking)


def test_a_transient_freed_outside_every_unit_interval_stays_unclassified(tmp_path):
    """No declared step boundary, so once-per-step and never-again are both fills."""
    def mutate(report):
        report["observations"]["torch_allocations"][0].update(
            free_requested_index=11, free_completed_index=12)
        report["observations"]["checkpoints"] = []
        report["partition"]["membership"] = [
            row for row in report["partition"]["membership"] if row["allocation_id"] != "0:4096:1"]
    verdict = consume(tmp_path, mutated(mutate))
    assert "0:4096:1" in verdict.unclassified_allocations
    assert any("no complete declared step boundary covers this capture" in reason
               for reason in verdict.blocking)


# --------------------------------------------------------------------------
# The arithmetic, on a fixture whose expected numbers are written by hand.
# --------------------------------------------------------------------------

#  id           alloc  free  bytes  lifetime_scope   owner        lifetime    unit
# The rows, and the owner/lifetime class each one carries. Ownership comes
# from the observed category and lifetime from whether the row is ever freed
# and which scope it was freed in; both are recomputed by the consumer, and
# stated here so the fixture says what it means rather than echoing the code.
CLOSED_ROWS = [
    # id,        alloc, free, bytes, lifetime scope,  owner,       lifetime,    unit
    ("0:1000:1",     1, None,  4096, "outside_units", "fixed",     "resident",   None),
    ("0:1100:1",     2, None,  2048, "outside_units", "kv",        "resident",   None),
    ("0:2000:1",    10,   14,  1000, "inside_unit",   "fixed",     "scratch",   "unit.a"),
    ("0:3000:1",    12,   20,  2000, "inside_unit",   "fixed",     "scratch",   "unit.a"),
    ("0:4000:1",    14,   18,  3000, "inside_unit",   "fixed",     "scratch",   "unit.a"),
    ("0:5000:1",    11,   13,   700, "inside_unit",   "candidate", "scratch",   "unit.a"),
    ("0:6000:1",    12,   16,   800, "inside_unit",   "candidate", "scratch",   "unit.a"),
    ("0:7000:1",    30,   34,  1200, "inside_unit",   "candidate", "scratch",   "unit.b"),
    ("0:8000:1",    34,   38,  1300, "inside_unit",   "candidate", "scratch",   "unit.b"),
    ("0:9000:1",    12,   40,   500, "escapes_unit",  "candidate", "activation", "unit.a"),
    ("0:9100:1",    31,   36,   900, "escapes_unit",  "candidate", "activation", "unit.b"),
    ("0:9200:1",    15, None,  1600, "inside_unit",   "candidate", "resident",  "unit.b"),
]
CLOSED_UNITS = ["unit.a", "unit.b"]
# Hand-computed from the intervals above, and confirmed against the producer's
# own `derive_partition` on these same rows, so the fixture states the other
# side's output rather than this consumer's:
#   fixed scratch  1000[10,14) 2000[12,20) 3000[14,18): 10>1000 12>3000
#                  14>free 1000 then take 3000 = 5000, 18>2000, 20>0.  Peak 5000.
#                  A sum of per-allocation maxima would be 6000.
#   unit.a scratch  700[11,13) 800[12,16): 11>700 12>1500 13>800.       Peak 1500.
#   unit.b scratch 1200[30,34) 1300[34,38): the free at 34 settles first. Peak 1300.
#   candidate_scratch is one charge per unit, not their max and not their sum.
CLOSED_FIXED_SCRATCH = 5000
CLOSED_CANDIDATE_SCRATCH = {"unit.a": 1500, "unit.b": 1300}
CLOSED_LIVE_PEAK = 14044


#: Two declared engine steps over the rows above: `unit.a` runs inside the
#: first and `unit.b` inside the second. The gaps -- before 8, between 24 and
#: 28, after 42 -- are where an off-step allocation lives.
CLOSED_STEPS = [("step:0", 8, 24), ("step:1", 28, 42)]
#: Allocated and freed before the first declared step, in no unit interval. It
#: is live during no engine step, so no composition term charges it and it is
#: priced on its own. 7000 bytes over [2, 6) never lifts the fixture's live
#: peak, which is 14044 and is reached later.
NON_STEP_ROWS = [("0:12000:1", 2, 6, 7000, "outside_units", "fixed", "non_step", None)]


def closed_report(*, steps=None, rows=()):
    """A report whose two checkable domains are closed.

    ``steps`` declares engine step intervals as ``(step_id, begin, end)`` and
    stamps complete coverage over them; without it the capture declares none,
    which is the state every fixture here carried before step intervals
    existed. ``rows`` appends allocations in the ``CLOSED_ROWS`` spelling.
    """
    allocations, membership, non_step = [], [], []
    for index, (ident, alloc, free, size, scope, owner, lifetime, unit) in enumerate(
            list(CLOSED_ROWS) + list(rows)):
        device, address, generation = ident.split(":")
        allocations.append({
            "address": int(address), "allocate_index": alloc, "allocation_id": ident,
            "allocator_block_bytes_observed": [size], "bytes": size,
            "free_completed_index": free,
            "free_requested_index": None if free is None else free - 1,
            "generation": int(generation), "lifetime_scope": scope,
            "observed_categories": [owner], "observed_owners": [f"owner.{index}"],
            "scope_stack": [] if unit is None else [unit],
            "unit_invocation": None if unit is None else f"{unit}:0",
        })
        entry = {"allocate_index": alloc, "allocation_id": ident, "bytes": size,
                 "free_completed_index": free, "lifetime_class": lifetime,
                 "owner_class": owner, "unit": unit}
        (non_step if lifetime == "non_step" else membership).append(entry)
    if steps is None:
        intervals = None
        coverage = {"declared": None, "executed": None, "state": "unobserved",
                    "reason": "this capture declared no engine step intervals"}
    else:
        intervals = [{"step_id": step_id, "begin_index": begin, "end_index": end}
                     for step_id, begin, end in steps]
        coverage = {"declared": len(steps), "executed": len(steps), "state": "complete",
                    "reason": None,
                    "scope": "engine execute_model invocations made while the observation "
                             "workload was armed"}
    non_step_peak = _simultaneous_peak_of(non_step)
    # Swept from the membership rows rather than restated, so an appended row
    # changes the fixture's own claim instead of contradicting it. The two
    # hand-computed constants above are asserted against this sweep in
    # `test_the_fixture_charges_the_hand_computed_peaks`, which is what keeps
    # the expected numbers independent of the consumer that recomputes them.
    terms = {name: None for name in TERMS}
    terms["fixed_scratch"] = _simultaneous_peak_of(
        [row for row in membership
         if row["owner_class"] == "fixed" and row["lifetime_class"] == "scratch"])
    terms["candidate_scratch"] = {
        unit: _simultaneous_peak_of(
            [row for row in membership if row["owner_class"] == "candidate"
             and row["lifetime_class"] == "scratch" and row["unit"] == unit])
        for unit in CLOSED_UNITS}
    domains = {name: {"state": "open", "evidence": [], "reason": "no implemented check"}
               for name in DOMAINS}
    # Each closed domain cites the observation its closing condition is read
    # from, which is now the only kind of evidence the envelope resolves.
    for name, evidence in (("history_join", "unattributed_external_records"),
                           ("external_closure", "external_native_peak_bytes")):
        domains[name] = {"state": "closed", "evidence": [evidence], "reason": None}
    scope = {"allocation_scope": "gpu_allocations_only", "expressible": False,
             "invariance": "one complete assignment, one row per unit",
             "topology": "tp1_single_device_resident_eager",
             "unavailable_terms": sorted(name for name in TERMS if terms[name] is None),
             "unclassified_allocation_count": 0, "uncharged_allocation_count": 0,
             "non_step_allocation_count": len(non_step), "step_coverage": coverage["state"]}
    identity = {"assignment_sha256": "a" * 64, "canonical_units_sha256": "a" * 64,
                "configuration_sha256": "a" * 64, "device_id": 0, "device_uuid": "synthetic-device",
                "model_sha256": "a" * 64, "runtime_manifest_sha256": "a" * 64,
                "schema": "tessera.full_engine_resource_identity.v1", "workload_sha256": "a" * 64}
    return {
        "schema": REPORT_SCHEMA,
        "identity": {"capture_sha256": "c" * 64,
                     "fixture_provenance": "synthetic CPU-only arithmetic fixture",
                     "run": copy.deepcopy(identity)},
        "reference": {"canonical_census": {"units": list(CLOSED_UNITS)},
                      "runtime_binding": {"member_formats": {}},
                      "selected_rows": [{"unit": "unit.a"}, {"unit": "unit.b"}]},
        "workload": {"calibration": {"sha256": "a" * 64},
                     "prompt_ids": [0, 1], "sampling": {"greedy": True}},
        "execution": {"graph_mode": "eager", "residency": "resident", "topology": "tp1"},
        "observations": {
            "artifacts": [], "capture_sha256": "c" * 64, "checkpoints": [],
            "cuda_argument_domains": {"handled_api_keys": ["cudaMalloc"], "host_allocations": [],
                                      "host_mappings": [], "issues": [], "null_device_frees": [],
                                      "scope": "observed pinned-host lifetimes", "status": "observed"},
            "external_native_peak_bytes": 2048, "issues": [],
            "kv_observations": None, "observer_qualification": None, "owner_views": None,
            "runtime_provenance_relation": None, "timing_captures": None,
            "worker_startup_records": None,
            "torch_allocations": allocations,
            "step_coverage": coverage, "step_intervals": intervals,
            # Swept over every observed allocation, so an appended row is
            # carried by the observation it changes instead of contradicting it.
            "torch_observed_live_peak_bytes": _simultaneous_peak_of(allocations),
            "torch_observed_live_peak_scope": "requested_allocation_bytes_excluding_allocator_rounding",
            "unattributed_external_records": []},
        "partition": {"capture_sha256": "c" * 64, "domains": copy.deepcopy(domains),
                      "domains_source": "derived",
                      "identity": copy.deepcopy(identity), "membership": membership,
                      "non_step_allocations": non_step,
                      "non_step_transient_peak_bytes": non_step_peak,
                      "non_step_transient_peak_scope": OPEN_STARTUP_PEAK_SCOPE,
                      "schema": "tessera.full_engine_resource_partition.v1",
                      "scope": copy.deepcopy(scope), "terms": copy.deepcopy(terms),
                      "uncharged_allocations": [],
                      "unclassified_allocations": [], "units": list(CLOSED_UNITS)},
        "derived": {"non_step_transient_peak_bytes": non_step_peak,
                    "non_step_transient_peak_scope": OPEN_STARTUP_PEAK_SCOPE,
                    "placement_obligation": PLACEMENT_OBLIGATION,
                    "scalar_budget_bytes": None, "scope": scope, "terms": terms},
    }


def _simultaneous_peak_of(rows):
    """The fixture's own sweep, so the expected number is not read from the
    consumer it checks. Frees settle before allocations at the same index."""
    events = []
    for row in rows:
        events.append((row["allocate_index"], 1, row["bytes"]))
        if row["free_completed_index"] is not None:
            events.append((row["free_completed_index"], 0, -row["bytes"]))
    live = peak = 0
    for _, _, delta in sorted(events, key=lambda event: (event[0], event[1])):
        live += delta
        peak = max(peak, live)
    return peak


def test_the_fixture_charges_the_hand_computed_peaks(tmp_path):
    """The constants above are the expected numbers; the fixture's sweep has to
    reproduce them before any test reads a term out of the consumer."""
    terms = closed_report()["derived"]["terms"]
    assert terms["fixed_scratch"] == CLOSED_FIXED_SCRATCH == 5000
    assert terms["candidate_scratch"] == CLOSED_CANDIDATE_SCRATCH


def test_the_fixture_observes_the_live_peak_it_was_written_against(tmp_path):
    """The hand-computed peak, so an appended row is visible as a change here
    rather than only inside the consumer that reads it."""
    report = closed_report()
    assert report["observations"]["torch_observed_live_peak_bytes"] == CLOSED_LIVE_PEAK == 14044
    assert consume(tmp_path, report).disagreements == ()


def test_a_peak_is_a_sweep_and_not_a_sum_of_per_allocation_maxima(tmp_path):
    verdict = consume(tmp_path, closed_report())
    assert verdict.disagreements == ()
    assert verdict.recomputed_terms["fixed_scratch"] == CLOSED_FIXED_SCRATCH == 5000
    assert verdict.recomputed_terms["fixed_scratch"] < 1000 + 2000 + 3000


def test_frees_settle_before_allocations_at_the_same_index(tmp_path):
    """unit.b frees 1200 at index 34 and allocates 1300 at index 34."""
    verdict = consume(tmp_path, closed_report())
    assert verdict.recomputed_terms["candidate_scratch"]["unit.b"] == 1300
    assert verdict.recomputed_terms["candidate_scratch"]["unit.b"] < 1200 + 1300


def test_a_candidate_term_is_one_charge_per_unit_and_not_a_reduction(tmp_path):
    """The term is the per-unit breakdown the declared invariance promises,
    "one complete assignment, one row per unit". Reducing it is the
    composition's job: `sum` for residency, `max` for the transients. A term
    that arrived already reduced could not be audited per unit, and two units
    trading the same bytes would look identical to two units that did not."""
    verdict = consume(tmp_path, closed_report())
    charges = verdict.recomputed_terms["candidate_scratch"]
    assert charges == CLOSED_CANDIDATE_SCRATCH == {"unit.a": 1500, "unit.b": 1300}
    assert set(charges) == set(CLOSED_UNITS)
    assert charges != max(charges.values())
    assert charges != sum(charges.values())


def test_a_per_unit_charge_that_differs_refuses_even_when_its_max_and_sum_agree(tmp_path):
    """The test that proves the comparison is per unit.

    unit.a and unit.b swap charges. `max` is 1500 either way and `sum` is 2800
    either way, so every reduction of this term agrees with the producer while
    both units are wrong. Only a unit-by-unit comparison sees it, and the
    refusal names the unit."""
    report = closed_report()
    swapped = {"unit.a": CLOSED_CANDIDATE_SCRATCH["unit.b"],
               "unit.b": CLOSED_CANDIDATE_SCRATCH["unit.a"]}
    assert max(swapped.values()) == max(CLOSED_CANDIDATE_SCRATCH.values())
    assert sum(swapped.values()) == sum(CLOSED_CANDIDATE_SCRATCH.values())
    report["derived"]["terms"]["candidate_scratch"] = swapped
    verdict = consume(tmp_path, report)
    assert any("candidate_scratch charges unit 'unit.a' 1300 where this consumer recomputes 1500"
               in reason for reason in verdict.disagreements)
    assert any("candidate_scratch charges unit 'unit.b' 1500 where this consumer recomputes 1300"
               in reason for reason in verdict.disagreements)


def test_a_per_unit_term_that_drops_a_unit_refuses(tmp_path):
    """Every unit gets a charge, including one whose charge is zero; a term
    that omits a unit is a term nothing can audit against the roster."""
    report = closed_report()
    report["derived"]["terms"]["candidate_scratch"] = {"unit.a": CLOSED_CANDIDATE_SCRATCH["unit.a"]}
    verdict = consume(tmp_path, report)
    assert any("candidate_scratch charges no unit 'unit.b'" in reason
               for reason in verdict.disagreements)


def test_a_per_unit_term_that_arrives_as_a_scalar_refuses(tmp_path):
    """A `max` where a mapping belongs is the defect this shape prevents."""
    report = closed_report()
    report["derived"]["terms"]["candidate_scratch"] = max(CLOSED_CANDIDATE_SCRATCH.values())
    with pytest.raises(RuntimePriceError, match="expected a per-unit charge table"):
        consume(tmp_path, report)


def test_a_fully_recomputing_report_still_expresses_no_scalar_budget(tmp_path):
    """Four of the six domains have no closing condition this schema emits, so
    at v1 the resident, activation and KV terms can never become numbers and
    the composition can never complete."""
    verdict = consume(tmp_path, closed_report())
    assert verdict.disagreements == ()
    assert verdict.expressible_terms == ("fixed_scratch", "candidate_scratch")
    assert verdict.recomputed_scalar_budget_bytes is None
    assert any("no scalar device budget is expressible" in reason for reason in verdict.blocking)


@pytest.mark.parametrize("wrong", [6000, CLOSED_FIXED_SCRATCH + 1, 0])
def test_a_changed_derived_total_on_an_agreeing_report_refuses(tmp_path, wrong):
    """The keystone on a report whose terms are genuinely expressible, so it
    cannot pass on all-null terms."""
    report = closed_report()
    assert report["derived"]["terms"]["fixed_scratch"] == CLOSED_FIXED_SCRATCH
    report["derived"]["terms"]["fixed_scratch"] = wrong
    verdict = consume(tmp_path, report)
    assert any(f"derived term fixed_scratch is {wrong}" in reason
               for reason in verdict.disagreements)


def test_a_kv_charge_refuses_while_its_own_domain_is_not_closed(tmp_path):
    """`kv` is a real owner class and the fixture carries a KV backing, so
    `fixed_kv` is recomputable arithmetic: the sum of the resident KV rows.
    What it waits on is `cache_capacity`, which no report closes at this
    schema version, so any number here is a charge the gate may not read."""
    report = closed_report()
    report["derived"]["terms"]["fixed_kv"] = 2048
    report["derived"]["scope"]["unavailable_terms"].remove("fixed_kv")
    verdict = consume(tmp_path, report)
    assert "cache_capacity" in verdict.open_domains
    assert any("derived term fixed_kv is 2048 where this consumer recomputes None" in reason
               for reason in verdict.disagreements)


def test_a_kv_backing_is_classified_rather_than_left_unclassified(tmp_path):
    """Dropping `kv` from the owner classes would unclassify a real row and
    null every term on any capture that has one."""
    verdict = consume(tmp_path, closed_report())
    assert verdict.unclassified_allocations == ()
    assert verdict.disagreements == ()


# --------------------------------------------------------------------------
# The three fields tessera#450 added after this consumer froze its field sets:
# `partition.domains_source`, `partition.uncharged_allocations` and
# `partition.scope.uncharged_allocation_count`.
# --------------------------------------------------------------------------

#: `0:5000:1` is a candidate scratch row charged to `unit.a`. Stripped of its
#: unit it stays classified and every candidate term, being keyed by unit,
#: reaches nothing that holds it.
UNCHARGED_ID = "0:5000:1"
UNCHARGED_ROW = {"allocation_id": UNCHARGED_ID, "bytes": 700, "owner_class": "candidate",
                 "lifetime_class": "scratch", "unit": None,
                 "reason": "a candidate allocation carrying no unit is charged by no per-unit term"}


def uncharged_report():
    """A closed report with exactly one classified row no term charges."""
    report = closed_report()
    for allocation in report["observations"]["torch_allocations"]:
        if allocation["allocation_id"] == UNCHARGED_ID:
            allocation["scope_stack"] = []
            allocation["unit_invocation"] = None
    for row in report["partition"]["membership"]:
        if row["allocation_id"] == UNCHARGED_ID:
            row["unit"] = None
    # Every term is null on both sides: an uncharged row is bytes the engine
    # holds that the seven-term composition never adds, so a composition over
    # them is short by exactly the amount nobody may notice.
    for member in (report["partition"], report["derived"]):
        member["terms"] = {name: None for name in TERMS}
        member["scope"]["unavailable_terms"] = sorted(TERMS)
        member["scope"]["expressible"] = False
        member["scope"]["uncharged_allocation_count"] = 1
        # An off-step price needs the same join a scratch term needs, and an
        # uncharged row could itself be off-step, so the price goes null while
        # the count stays readable.
        member["non_step_transient_peak_bytes"] = None
    report["partition"]["uncharged_allocations"] = [dict(UNCHARGED_ROW)]
    return report


def test_a_partition_whose_domains_were_supplied_refuses_by_name(tmp_path):
    """Supplied domains close because a caller passed them, not on evidence,
    and a report assembled over them would emit every term on that word."""
    def mutate(report):
        report["partition"]["domains_source"] = "supplied"
    with pytest.raises(RuntimePriceError, match="domains_source is 'supplied'"):
        consume(tmp_path, mutated(mutate))


def test_an_unknown_domains_source_refuses_rather_than_being_read_as_derived(tmp_path):
    def mutate(report):
        report["partition"]["domains_source"] = "measured"
    with pytest.raises(RuntimePriceError, match="domains source: unknown value 'measured'"):
        consume(tmp_path, mutated(mutate))


def test_the_supplied_report_carries_the_three_added_fields_and_still_recomputes(tmp_path):
    """The fields tessera#450 added are declared here, so the frozen envelope
    reads instead of refusing every report the producer now builds."""
    report = supplied()
    assert report["partition"]["domains_source"] == "derived"
    assert report["partition"]["uncharged_allocations"] == []
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        assert scope["uncharged_allocation_count"] == 0
    verdict = consume(tmp_path, report)
    assert verdict.disagreements == ()


def test_an_uncharged_allocation_the_producer_omits_refuses_because_the_consumer_derives_it(tmp_path):
    """The producer's list is a claim. Undercounting is the one error
    direction that must never be silent: it hands a gate a budget smaller than
    the engine needs, and on unified memory that is an OOM."""
    report = uncharged_report()
    report["partition"]["uncharged_allocations"] = []
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        scope["uncharged_allocation_count"] = 0
    verdict = consume(tmp_path, report)
    assert any("uncharged allocations are not the ones this consumer finds no term charges" in reason
               for reason in verdict.disagreements), verdict.disagreements


def test_an_uncharged_count_that_disagrees_with_its_own_list_refuses(tmp_path):
    report = uncharged_report()
    report["partition"]["scope"]["uncharged_allocation_count"] = 0
    report["derived"]["scope"]["uncharged_allocation_count"] = 4
    verdict = consume(tmp_path, report)
    for member in ("partition", "derived"):
        assert any(f"the {member} scope claims another uncharged allocation count" in reason
                   for reason in verdict.disagreements), verdict.disagreements


def test_an_uncharged_allocation_placed_in_another_cell_refuses(tmp_path):
    """Set membership alone would pass a row whose owner or unit was restated."""
    report = uncharged_report()
    report["partition"]["uncharged_allocations"][0]["unit"] = "unit.a"
    verdict = consume(tmp_path, report)
    assert any(f"uncharged allocation {UNCHARGED_ID} is placed in another cell" in reason
               for reason in verdict.disagreements), verdict.disagreements


def test_an_uncharged_allocation_nulls_every_term_and_blocks_the_budget(tmp_path):
    """`fixed_scratch` and `candidate_scratch` are otherwise expressible on
    this fixture, so a term surviving here would be a composition that omits
    an allocation and says nothing."""
    assert consume(tmp_path, closed_report()).expressible_terms == ("fixed_scratch",
                                                                    "candidate_scratch")
    verdict = consume(tmp_path, uncharged_report())
    assert verdict.disagreements == ()
    assert verdict.expressible_terms == ()
    assert verdict.recomputed_scalar_budget_bytes is None
    assert any(f"allocation {UNCHARGED_ID} is classified (candidate, scratch) but no term "
               "charges it" in reason for reason in verdict.blocking), verdict.blocking


def test_an_uncharged_row_naming_no_classified_allocation_refuses(tmp_path):
    """Uncharged rows restate membership rows; one that names nothing is a
    fourth partition of an allocation this report never classified."""
    def mutate(report):
        report["partition"]["uncharged_allocations"] = [dict(UNCHARGED_ROW, allocation_id="0:1:9")]
    with pytest.raises(RuntimePriceError, match="uncharged allocation '0:1:9' is not a classified"):
        consume(tmp_path, mutated(mutate))


def test_the_reader_returns_the_report_it_validated(tmp_path):
    report = closed_report()
    assert read_full_engine_resource_report(written(tmp_path, report), root=tmp_path) == report


# --------------------------------------------------------------------------
# Step-scoped ownership (tessera#451). A declared engine step is what licenses
# the off-step class: without one, an allocation freed outside every unit
# interval is unclassified, and with a partial one it stays unclassified,
# because a row live during no *declared* step may be live during an
# undeclared one.
# --------------------------------------------------------------------------

def test_the_stepped_synthetic_report_round_trips_with_complete_coverage(tmp_path):
    """The producer's own output for a capture that declared its engine step."""
    report = stepped()
    assert report["observations"]["step_coverage"]["state"] == "complete"
    assert report["observations"]["step_intervals"] == [
        {"step_id": "step:0", "begin_index": 3, "end_index": 8}]
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        assert scope["step_coverage"] == "complete"
    assert report["derived"]["placement_obligation"] == PLACEMENT_OBLIGATION
    verdict = consume(tmp_path, report)
    assert verdict.disagreements == ()
    assert "synthetic" in verdict.fixture_provenance


def test_the_supplied_report_declares_no_step_and_says_so(tmp_path):
    report = supplied()
    assert report["observations"]["step_intervals"] is None
    assert report["observations"]["step_coverage"]["state"] == "unobserved"
    verdict = consume(tmp_path, report)
    assert verdict.disagreements == ()
    assert any("step coverage is 'unobserved'" in reason for reason in verdict.blocking)


def test_an_allocation_contained_in_one_declared_step_is_step_scratch(tmp_path):
    """Outside every unit interval, inside one step: charged once per step."""
    row = ("0:13000:1", 9, 23, 400, "outside_units", "fixed", "scratch", None)
    verdict = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=[row]))
    assert verdict.disagreements == ()
    assert verdict.recomputed_non_step_transient_peak_bytes == 0
    # 400 bytes live over [9, 23) never overlap the fixed scratch peak at 14.
    assert verdict.recomputed_terms["fixed_scratch"] == CLOSED_FIXED_SCRATCH + 400


def test_an_allocation_live_across_a_step_boundary_is_carried_not_scratch(tmp_path):
    """Overlapping a step without being contained in one is an activation:
    the bytes survive the boundary, exactly as a row outliving its unit does."""
    row = ("0:13000:1", 20, 30, 400, "outside_units", "fixed", "activation", None)
    verdict = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=[row]))
    # No disagreement means the consumer put the row in the `activation` cell
    # the fixture declares for it. The term itself stays null: every activation
    # term depends on `worker_startup`, which never closes at this version.
    assert verdict.disagreements == ()
    assert verdict.recomputed_terms["fixed_activation"] is None
    assert verdict.recomputed_terms["fixed_scratch"] == CLOSED_FIXED_SCRATCH
    assert verdict.recomputed_non_step_transient_peak_bytes == 0


def test_an_allocation_live_during_no_declared_step_is_priced_but_never_charged(tmp_path):
    """It is named, counted and priced beside the composition, not inside it.
    The seven terms price one engine step and it is live during none of them."""
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    assert [row["allocation_id"] for row in report["partition"]["non_step_allocations"]] == \
        ["0:12000:1"]
    verdict = consume(tmp_path, report)
    assert verdict.disagreements == ()
    assert verdict.recomputed_non_step_transient_peak_bytes == 7000
    assert verdict.recomputed_terms["fixed_scratch"] == CLOSED_FIXED_SCRATCH
    assert verdict.recomputed_terms["candidate_scratch"] == CLOSED_CANDIDATE_SCRATCH
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        assert scope["non_step_allocation_count"] == 1


def test_partial_step_coverage_refuses_the_same_row_the_complete_one_classifies(tmp_path):
    """Partial and unobserved behave identically, which is how this consumer
    behaved before any step could be declared at all."""
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    report["observations"]["step_coverage"].update(
        executed=3, state="partial",
        reason="a step interval was declared for only some of the engine steps this "
               "capture executed")
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        scope["step_coverage"] = "partial"
    verdict = consume(tmp_path, report)
    assert verdict.unclassified_allocations == ("0:12000:1",)
    assert verdict.recomputed_terms == {name: None for name in TERMS}
    assert verdict.recomputed_non_step_transient_peak_bytes is None
    assert any("step coverage is 'partial'" in reason for reason in verdict.blocking)
    assert any("no complete declared step boundary covers this capture" in reason
               for reason in verdict.blocking)


def test_a_declared_interval_spanning_two_steps_refuses(tmp_path):
    """Two steps that overlap contradict each other about which step an
    allocation was live during, so neither bounds it."""
    def mutate(report):
        report["observations"]["step_intervals"] = [
            {"step_id": "step:0", "begin_index": 8, "end_index": 40},
            {"step_id": "step:1", "begin_index": 28, "end_index": 42}]
    with pytest.raises(RuntimePriceError, match="spans the extent of step 'step:1'"):
        consume(tmp_path, mutate_stepped(mutate))


def test_a_unit_invocation_spanning_two_steps_refuses(tmp_path):
    """The other reading of the same contradiction. A unit runs inside one
    engine step, so the producer refuses a unit interval that overlaps a step
    without being contained in it. The report carries no unit intervals, so the
    contradiction is read off an allocation that ran inside one: it is live over
    [20, 30), which overlaps both declared steps and is contained in neither."""
    row = ("0:15000:1", 20, 30, 400, "inside_unit", "fixed", "scratch", "unit.a")
    verdict = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=[row]))
    assert verdict.disagreements == (
        "allocation 0:15000:1 ran inside a unit invocation that spans a declared "
        "step boundary, which no capture may declare",)


def test_a_unit_invocation_inside_one_step_is_not_a_crossing(tmp_path):
    """The same row moved inside `step:0` is the control: the check bites on
    the crossing rather than on every allocation that names a unit."""
    row = ("0:15000:1", 20, 23, 400, "inside_unit", "fixed", "scratch", "unit.a")
    verdict = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=[row]))
    assert verdict.disagreements == ()


def test_a_declared_interval_that_is_reversed_or_empty_refuses(tmp_path):
    def mutate(report):
        report["observations"]["step_intervals"][0]["end_index"] = 8
    with pytest.raises(RuntimePriceError, match="step 'step:0' is reversed or unclosed"):
        consume(tmp_path, mutate_stepped(mutate))


def test_a_duplicate_step_identity_refuses(tmp_path):
    def mutate(report):
        report["observations"]["step_intervals"][1]["step_id"] = "step:0"
    with pytest.raises(RuntimePriceError, match="duplicate step 'step:0'"):
        consume(tmp_path, mutate_stepped(mutate))


def test_a_coverage_state_its_own_counts_do_not_support_refuses(tmp_path):
    """`complete` is a claim like any other. A capture that ran three steps and
    declared two has not covered them, whatever the state field says."""
    def mutate(report):
        report["observations"]["step_coverage"]["executed"] = 3
    with pytest.raises(RuntimePriceError, match="claims 'complete' where its own declared"):
        consume(tmp_path, mutate_stepped(mutate))


def test_a_declared_step_count_that_disagrees_with_the_intervals_carried_refuses(tmp_path):
    def mutate(report):
        report["observations"]["step_coverage"]["declared"] = 5
    with pytest.raises(RuntimePriceError, match="declares 5 steps where the report carries 2"):
        consume(tmp_path, mutate_stepped(mutate))


def test_step_intervals_without_a_coverage_claim_over_them_refuse(tmp_path):
    def mutate(report):
        report["observations"]["step_coverage"] = {
            "declared": None, "executed": None, "state": "unobserved",
            "reason": "this capture declared no engine step intervals"}
    with pytest.raises(RuntimePriceError, match="carried exactly when the coverage state"):
        consume(tmp_path, mutate_stepped(mutate))


def test_an_unobserved_coverage_claim_that_counts_steps_refuses(tmp_path):
    def mutate(report):
        report["observations"]["step_coverage"]["declared"] = 2
    with pytest.raises(RuntimePriceError, match="counts declared or executed steps"):
        consume(tmp_path, mutated(mutate))


def test_an_off_step_peak_that_disagrees_with_the_recomputation_refuses_by_name(tmp_path):
    """`derived` is a claim. A producer that prices its own off-step bytes
    lower than the sweep over them hands a placement the smaller number."""
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    report["derived"]["non_step_transient_peak_bytes"] = 1
    report["partition"]["non_step_transient_peak_bytes"] = 7000
    verdict = consume(tmp_path, report)
    assert any("derived non_step_transient_peak_bytes is 1 where this consumer recomputes 7000"
               in reason for reason in verdict.disagreements), verdict.disagreements


def test_an_off_step_allocation_the_producer_omits_refuses(tmp_path):
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    report["partition"]["non_step_allocations"] = []
    report["partition"]["non_step_transient_peak_bytes"] = 0
    report["derived"]["non_step_transient_peak_bytes"] = 0
    for scope in (report["partition"]["scope"], report["derived"]["scope"]):
        scope["non_step_allocation_count"] = 0
    verdict = consume(tmp_path, report)
    assert any("off-step allocations are not the ones this consumer finds" in reason
               for reason in verdict.disagreements), verdict.disagreements


def test_an_off_step_count_that_disagrees_with_its_own_list_refuses(tmp_path):
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    report["partition"]["scope"]["non_step_allocation_count"] = 0
    report["derived"]["scope"]["non_step_allocation_count"] = 4
    verdict = consume(tmp_path, report)
    for member in ("partition", "derived"):
        assert any(f"the {member} scope claims another off-step allocation count" in reason
                   for reason in verdict.disagreements), verdict.disagreements


def test_a_scope_restating_the_coverage_state_refuses(tmp_path):
    def mutate(report):
        report["partition"]["scope"]["step_coverage"] = "partial"
    verdict = consume(tmp_path, mutate_stepped(mutate))
    assert any("scope claims step coverage 'partial' where the observations declare 'complete'"
               in reason for reason in verdict.disagreements), verdict.disagreements


def test_the_placement_obligation_is_a_frozen_contract_spelling(tmp_path):
    """A gate reads this string, so it is compared verbatim rather than as prose."""
    def mutate(report):
        report["derived"]["placement_obligation"] = "scalar_budget_bytes"
    verdict = consume(tmp_path, mutated(mutate))
    assert any("derived placement_obligation is 'scalar_budget_bytes'" in reason
               for reason in verdict.disagreements), verdict.disagreements


@pytest.mark.parametrize("budget,peak,expected", [
    (10, 4, 10), (4, 10, 10), (10, 10, 10), (0, 0, 0),
    (None, 4, None), (10, None, None), (None, None, None)])
def test_the_placement_obligation_moves_with_each_side(budget, peak, expected):
    """Both sides are obligations on the same box, and neither is defaulted to
    zero: an absent side is an absence of evidence, and a maximum taken against
    it would read as the other side having been checked."""
    assert _placement_obligation(budget, peak) == expected


def test_the_placement_obligation_is_null_while_either_side_is(tmp_path):
    """At this schema version `fixed_resident` depends on `worker_startup`,
    which never closes, so the budget side is null on every report the producer
    can emit. The obligation is therefore null and refuses by name."""
    verdict = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS))
    assert verdict.recomputed_non_step_transient_peak_bytes == 7000
    assert verdict.recomputed_scalar_budget_bytes is None
    assert verdict.recomputed_placement_obligation_bytes is None
    assert any("no placement obligation is recomputable" in reason
               for reason in verdict.blocking)


def test_an_allocation_is_charged_to_the_outermost_unit_its_lifetime_was_decided_against(tmp_path):
    """Unit intervals nest, and the producer reads `unit_invocation` from the
    outermost one and decides `lifetime_scope` against that same interval.
    Charging the innermost would split a row's lifetime basis from its charge
    and put simultaneously live rows into two buckets a maximum chooses between."""
    report = closed_report()
    for allocation in report["observations"]["torch_allocations"]:
        if allocation["allocation_id"] == "0:5000:1":
            allocation["scope_stack"] = ["unit.a", "unit.a.attention"]
    verdict = consume(tmp_path, report)
    assert verdict.disagreements == ()
    assert verdict.recomputed_terms["candidate_scratch"] == CLOSED_CANDIDATE_SCRATCH


def mutate_stepped(mutate):
    """A two-step complete-coverage report with one off-step row, mutated."""
    report = closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS)
    mutate(report)
    return report


def test_both_committed_fixtures_declare_themselves_synthetic(tmp_path):
    """Neither file may ever read as evidence of a real capture."""
    for report in (supplied(), stepped()):
        assert "synthetic" in report["identity"]["fixture_provenance"]
        verdict = consume(tmp_path, report)
        assert any("is not a measurement" in reason for reason in verdict.blocking)


def test_the_off_step_price_moves_with_the_bytes_it_prices(tmp_path):
    """The off-step side of the placement obligation is a sweep over observed
    rows, so more off-step bytes raise it. Together with the pure maximum
    above, this is what makes the obligation move from either side."""
    bigger = [("0:12000:1", 2, 6, 9000, "outside_units", "fixed", "non_step", None)]
    small = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=NON_STEP_ROWS))
    large = consume(tmp_path, closed_report(steps=CLOSED_STEPS, rows=bigger))
    assert small.recomputed_non_step_transient_peak_bytes == 7000
    assert large.recomputed_non_step_transient_peak_bytes == 9000
    assert _placement_obligation(6000, small.recomputed_non_step_transient_peak_bytes) == 7000
    assert _placement_obligation(6000, large.recomputed_non_step_transient_peak_bytes) == 9000
    # And the budget side moves it too, with the off-step side held fixed.
    assert _placement_obligation(12000, small.recomputed_non_step_transient_peak_bytes) == 12000
